
log:
  writers: stdout              # Output destination —— file and stdout
  logger_level: INFO           # Log level: DEBUG, INFO, WARN, ERROR, FATAL
  logger_dir: log              # Log file directory
  log_rotate_date: 1           # Log rotate date
  log_rotate_size: 1           # Log rotate size

port:
  - 80

#tls:
#  - port: 443
#    cert: fullchain.cer
#    key: cdnbye.com.key

#redis:
#  enable: true
#  host: 127.0.0.1
#  port: 6379
#  dbname: 0
#  is_cluster: false
#  cluster:
#    - host: 127.0.0.1
#      port: 6379
#    - host: 127.0.0.1
#      port: 6380

ratelimit:
  enable: false
  max_rate: 400                # max requests per second

stats:
  enable: true
#  token: 123456           # Custom token for requesting stats info

compact:
  enable: true

compression:
  enable: false

node:
  msg_consume_interval: 60
  max_pipe_length: 800






